name: Qt CMake Windows Workflow

on:
  push:
    branches:
      - main
  pull_request:

env:
  QT_VERSION: 6.6.0
  CMAKE_VERSION: 3.5

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Qt
        uses: jurplel/install-qt-action@v1
        with:
          version: ${{ env.QT_VERSION }}
          components: qtbase, qtnetwork

      - name: Set up CMake
        uses: kitware/setup-cmake@v1
        with:
          cmakeVersion: ${{ env.CMAKE_VERSION }}

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Debug

      - name: Deploy
        run: |
          cd build
          windeployqt --no-compiler-runtime --dir deploy PCECDI_v6.exe
